### ISSUE TITLE
Get Serial Number

### ISSUE THREAD

**Issue by xcthulhu** [TESScience/tessfpe#14]
There should be a tool for getting the Serial Number from an FPE board.

**Comment by noqsi** [comment]
On Apr 11, 2016, at 9:11 AM, Matthew Wampler-Doty notifications@github.com wrote:

> There should be a tool for getting the Serial Number from an FPE board.

The Interface board serial number appears in the CAM_ID field (bits 10:6) of the FPGA VERSION. The firmware version (FW_version, bits 5:3) and the board version (BD_VERSION, bits 2:0) are also present, although the last is strange because there's no way for the FPGA to tell which version of the board it's operating.

The VERSION register is (read only) register 0x0D.

The data also appears in "status byte 2" (in the video data stream?) in a different packing.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub

John Doty              Noqsi Aerospace, Ltd.
http://www.noqsi.com/
jpd@noqsi.com

**Comment by noqsi** [comment]
I want to reiterate the point John made below, so no one thinks they’re getting more information than they are:

> there's no way for the FPGA to tell which version of the board it's operating

The BD_VERSION is an internal hard-coded value, like FW_VERSION, that specifies the board the FW should work on. This was put in early on so I could make sure any reported problems weren’t due to the fact that several of the board incarnations has different pinouts, so not all FW would run on all boards.

Going forward, this isn’t useful, since the FW from 6.1t and beyond is interchangeable on all boards (6.1t, 6.2, 7.0, …) since the pinout hasn’t changed.
