### ISSUE TITLE
Operating parameters don't actually change

### ISSUE THREAD

**Issue by ebokhour** [TESScience/tessfpe#2]
When changing operating parameters using the python tool, it outputs a listing which correctly shows the new values.  However, if I immediately read the housekeeping, it shows the default values, as if the change was never made.  This seems to be true of other parameters, too.  I confirmed that no change is made in the hardware by measuring current in the trim heater dummy load after changing the current to 100 mA, or to 227 mA.  This may be due to a very recent change, since yesterday we did observe current in the trim heater dummy load.

**Comment by xcthulhu** [comment]
I'm looking into it.

In the future, please provide a script to reproduce the bug...

**Comment by ebokhour** [comment]
Verified OK.

**Comment by TESSUser** [comment]
After updating caladan with git pull origin master, the bug is still present. The attached script should run but fails.  It did work, briefly, before the issue was closed this morning.

`#!/bin/bash
#This is a script used to reproduce the bug in TESScience/tessfpe Issue #2.

set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PYTHON=${DIR}/python

load_wrapper 6.1t.5
operating_parameters --set heater_1_current 100
house_keeping --channels heater_1_current`

**Comment by TESSUser** [comment]
I realize I'm running these shell scripts from the tessfpe/scripts directory, and most of your shell scripts call the Python scripts located in $DIR/python.  Is that the problem?

**Comment by TESSUser** [comment]
Needed to Make the install again.  Works now.
